"""
AI Mata (Maya) — Vision Agent Backend

A real-time vision agent powered by the GetStream Vision Agents SDK.
Maya watches through the camera, listens to you, and responds with
witty, sarcastic, overprotective Indian-mother energy.

Stack:
  - gemini.VLM       → Analyzes live video frames (food, room, etc.)
  - deepgram.STT      → Transcribes user speech
  - elevenlabs.TTS    → Maya speaks back with a real voice
  - getstream.Edge    → Real-time video/audio transport (WebRTC)
"""

import logging
import os
import jwt
from fastapi import Request, HTTPException, status
from fastapi.responses import JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware

from dotenv import load_dotenv
from vision_agents.core import Agent, AgentLauncher, Runner, User
from vision_agents.plugins import deepgram, elevenlabs, gemini, getstream

from .prompts import MOTHER_SYSTEM_PROMPT

logger = logging.getLogger(__name__)

load_dotenv()

# We use the same secret for GetStream and our own API auth for simplicity in this demo,
# or a dedicated API_SECRET if provided.
API_SECRET = os.environ.get("STREAM_API_SECRET", "default_secret_if_not_set")

class JWTAuthMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        # Only protect the /session/start endpoint (or any endpoint created by Runner)
        # The Runner defines /session/start natively
        if request.url.path == "/session/start":
            auth_header = request.headers.get("Authorization")
            if not auth_header or not auth_header.startswith("Bearer "):
                return JSONResponse(
                    status_code=status.HTTP_401_UNAUTHORIZED,
                    content={"detail": "Missing or invalid Authorization header"}
                )
            
            token = auth_header.split(" ")[1]
            try:
                # We expect the token to be signed with our API_SECRET 
                # (You can use the token generated by generate_dev_token.py for the Android app)
                jwt.decode(token, API_SECRET, algorithms=["HS256"])
            except jwt.ExpiredSignatureError:
                return JSONResponse(
                    status_code=status.HTTP_401_UNAUTHORIZED,
                    content={"detail": "Token has expired"}
                )
            except jwt.InvalidTokenError:
                return JSONResponse(
                    status_code=status.HTTP_401_UNAUTHORIZED,
                    content={"detail": "Invalid token"}
                )
        
        return await call_next(request)


async def create_agent(**kwargs) -> Agent:
    """
    Factory function called by the Runner/AgentLauncher to create a new Maya agent
    for each incoming session/call.
    """

    # Vision Language Model — watches video frames and understands visual context
    vlm = gemini.VLM(
        model="gemini-2.0-flash",
        fps=1,
        frame_buffer_seconds=5,
    )

    agent = Agent(
        edge=getstream.Edge(),
        agent_user=User(name="Maya", id="maya-ai-mata"),
        instructions=MOTHER_SYSTEM_PROMPT,
        processors=[],
        llm=vlm,
        tts=elevenlabs.TTS(),
        stt=deepgram.STT(eager_turn_detection=True),
    )

    return agent


async def join_call(agent: Agent, call_type: str, call_id: str, **kwargs) -> None:
    """
    Called when a session starts. The agent joins the GetStream call
    and sends an initial greeting as Maya.
    """
    call = await agent.create_call(call_type, call_id)

    async with agent.join(call):
        # Maya's opening line when she first connects
        await agent.simple_response(
            "You just connected to the camera. Look at what's in front of you "
            "and give your first reaction as Maya — comment on the room, "
            "any food you see, or whatever catches your eye first."
        )
        await agent.finish()


if __name__ == "__main__":
    import uvicorn
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("command", nargs="?", default="serve")
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=8000)
    args = parser.parse_args()

    # Create the baseline Runner
    runner = Runner(
        AgentLauncher(
            create_agent=create_agent,
            join_call=join_call,
        )
    )

    if args.command == "serve":
        # Runner natively exposes .app which is a regular FastAPI instance
        app = runner.app
        # Add our custom authentication middleware
        app.add_middleware(JWTAuthMiddleware)
        
        logger.info(f"Starting secured AI Mata server on {args.host}:{args.port}")
        uvicorn.run(app, host=args.host, port=args.port)
    else:
        # Fallback to default CLI behavior for things like 'dev'
        runner.cli()
